language: php

dist: trusty

sudo: false

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true

before_script:
  - composer self-update


# commands that will verify build
script:
  - ./vendor/bin/php-cs-fixer fix src
  - ./vendor/bin/phpunit --testdox --coverage-html test/coverage
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

# Customize when the notification emails are sent.
notifications:
  email:
    recipients:
      - angelyx@live.fr
    on_success: never # default: change
    on_failure: always # default: always

# safelist
branches:
  only:
    - dev

cache:
  directories:
    - $HOME/.composer/cache
